name: newrecipe

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - gh-pages

jobs:
  convertrecipesintohtml:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code from the repository
      - uses: actions/checkout@v3
      
      # Step 2: Set up PHP (install PHP 8.2)
      - uses: nanasess/setup-php@v4
        with:
          php-version: '8.2'

      # Step 3: Run the PHP script
      - run: php deployment/callallrecipesintohtml.php
